// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package client

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Help    *string `json:"help,omitempty"`
	Message *string `json:"message,omitempty"`
	Ok      bool    `json:"ok"`
}

// Location defines model for Location.
type Location struct {
	Latitude  *float64 `json:"latitude,omitempty"`
	Longitude *float64 `json:"longitude,omitempty"`
}

// MeasuringPoint defines model for MeasuringPoint.
type MeasuringPoint struct {
	Active              *bool     `json:"active,omitempty"`
	AlarmPercentage     *int      `json:"alarm_percentage,omitempty"`
	Category            *string   `json:"category,omitempty"`
	DataSaveLevel       *float32  `json:"data_save_level,omitempty"`
	DisableLed          *bool     `json:"disable_led,omitempty"`
	GuideLine           *string   `json:"guide_line,omitempty"`
	Id                  *int      `json:"id,omitempty"`
	MeasurementDuration *int      `json:"measurement_duration,omitempty"`
	MeasuringType       *string   `json:"measuring_type,omitempty"`
	Name                *string   `json:"name,omitempty"`
	TracePostTrigger    *int      `json:"trace_post_trigger,omitempty"`
	TracePreTrigger     *int      `json:"trace_pre_trigger,omitempty"`
	TraceSaveLevel      *int      `json:"trace_save_level,omitempty"`
	UserLocation        *Location `json:"user_location,omitempty"`
	VibrationType       *string   `json:"vibration_type,omitempty"`
}

// Sensor defines model for Sensor.
type Sensor struct {
	ConnectedUsing *string         `json:"connected_using,omitempty"`
	Lastseen       *time.Time      `json:"lastseen,omitempty"`
	Location       *Location       `json:"location,omitempty"`
	MeasuringPoint *MeasuringPoint `json:"measuring_point,omitempty"`
	Name           *string         `json:"name,omitempty"`
}

// SuccessResponse defines model for SuccessResponse.
type SuccessResponse struct {
	Ok      bool      `json:"ok"`
	Sensors *[]Sensor `json:"sensors,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListSensors request
	ListSensors(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListSensors(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListSensorsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListSensorsRequest generates requests for ListSensors
func NewListSensorsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/list_sensors")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListSensorsWithResponse request
	ListSensorsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListSensorsResponse, error)
}

type ListSensorsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SuccessResponse
	JSON400      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListSensorsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListSensorsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListSensorsWithResponse request returning *ListSensorsResponse
func (c *ClientWithResponses) ListSensorsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListSensorsResponse, error) {
	rsp, err := c.ListSensors(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListSensorsResponse(rsp)
}

// ParseListSensorsResponse parses an HTTP response from a ListSensorsWithResponse call
func ParseListSensorsResponse(rsp *http.Response) (*ListSensorsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListSensorsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SuccessResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get a list of active sensors
	// (GET /list_sensors)
	ListSensors(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListSensors converts echo context to params.
func (w *ServerInterfaceWrapper) ListSensors(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListSensors(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/list_sensors", wrapper.ListSensors)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xVTW/jNhD9K8S0hxZQLW+3veiWAkVhNIsGCXoKAmEsjWXuUiQzHAo1FvrvBSnHH7Hc",
	"BEXRkw3OB9+89zj6Co3rvbNkJUD1FUKzpR7z31+ZHd9T8M4GSgeenScWTTm8JePT78ZxjwIVRNZQgOw8",
	"QQVBWNsOxgJ6CgG73OAi5r6kY/oLe28Iqg2aQIcWa+cMoYVxLIDpOWqmFqrHVPR0SHLrz9RI6nXrGhTt",
	"7CVSg6IltnSGtnVxbegI2MZ+TZwaGWe79+ePM1A+EYaYZrxz2solIGxED6eMHEYtAA1yX3vihqyc86at",
	"UDdhbFCoc7ybZbVFwTrgQLWhgcxJznHIVgdcm5TRzuPoom6pNtrOK6fbeWB9Hp16slK3kQ+KXMvUtqun",
	"2MwlFvv5gDA2VHsXpBbWXeo4e8c+j+k9abOMnWTFQFybE5d9y7SBCr4pj0+o3L+f8uDGsYBBrycirk06",
	"56EHssHxpXcaZy01Qm0dQyqeo8dgkEBkzw2MQj+I7mnukf6bsY4C+heb/1Ppq0dxXd5ZNmLTUAjXt9Gr",
	"TSIcZxZJASGzmiu0UB/eAr1X4QgJmXH3vpWUr2sia9k9pHYT0Buvf6fdTZRtBmGhgudIvIMXPkDcF7JH",
	"kTAXwJj6tRQa1n5SCm7uVmrjWGHmRttO/dFb3ToJKhAPuqGgtG1MbFNsGl2l5bCAArTduEy+lkQYHEpv",
	"7lZQwEAcpls+LJaLZV7Wnix6DRV8XCwXH6EAj7LNQ5VGB6lPyO0o+yEplP2yaqGCWx3kYZ+T+Ju0zPk/",
	"Lpd7cwtNVkLvjZ7MVn4OkzMnVd7U7JVX5phTCbByGzWtYvUCfSzgp/8QyvkndAbIL9iqe3qOFER9t7ID",
	"Gt2qO2TsSYiDcqw+6Unb4+n3CebP/yfMlRVii0Y9EA/EKhecORyqx3NvPz6NTwWE2PeYPlPwG4nCq7RP",
	"rVLvkDtFNlDBVsRXZfnn/W2JXpfDBxifxr8DAAD//4SznUGyCAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
